[package]
name = "ggo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
clap = { version = "4.5", features = ["derive"] }
dirs = "5.0"
fuzzy-matcher = "0.3"
inquire = "0.7"
rusqlite = { version = "0.31", features = ["bundled"] }
